// Mock data for MVP demonstration
// These provide realistic sample data for demos when real data is not available

export const mockLeads = [
  {
    id: "mock-1",
    contractor_name: "Prefeitura de São Paulo",
    contractor_type: "Prefeitura",
    city: "São Paulo",
    state: "SP",
    venue_name: "Anhangabaú",
    event_date: "2026-03-15",
    fee: 150000,
    stage: "Negociação",
    contact_phone: "(11) 99999-1234",
    contact_email: "eventos@prefsp.gov.br",
    notes: "Show de aniversário da cidade",
    latitude: -23.5505,
    longitude: -46.6333,
  },
  {
    id: "mock-2",
    contractor_name: "Villa Country",
    contractor_type: "Casa de Show",
    city: "São Paulo",
    state: "SP",
    venue_name: "Villa Country",
    event_date: "2026-02-28",
    fee: 85000,
    stage: "Proposta",
    contact_phone: "(11) 98888-5678",
    contact_email: "shows@villacountry.com.br",
    notes: "Show sertanejo sexta-feira",
    latitude: -23.5256,
    longitude: -46.6776,
  },
  {
    id: "mock-3",
    contractor_name: "Festa do Peão de Barretos",
    contractor_type: "Festival",
    city: "Barretos",
    state: "SP",
    venue_name: "Arena Barretos",
    event_date: "2026-08-22",
    fee: 280000,
    stage: "Contato",
    contact_phone: "(17) 97777-9012",
    contact_email: "artistas@festapeaobarretos.com.br",
    notes: "Principal festival do país",
    latitude: -20.5544,
    longitude: -48.5678,
  },
  {
    id: "mock-4",
    contractor_name: "Rodeio de Jaguariúna",
    contractor_type: "Festival",
    city: "Jaguariúna",
    state: "SP",
    venue_name: "Parque de Eventos",
    event_date: "2026-05-10",
    fee: 200000,
    stage: "Fechado",
    contact_phone: "(19) 96666-3456",
    contact_email: "contato@rodeio.com.br",
    notes: "Contrato assinado - show confirmado",
    latitude: -22.7059,
    longitude: -47.0025,
  },
  {
    id: "mock-5",
    contractor_name: "Wood's Bar",
    contractor_type: "Casa de Show",
    city: "São Paulo",
    state: "SP",
    venue_name: "Wood's SP",
    event_date: "2026-02-14",
    fee: 65000,
    stage: "Prospecção",
    contact_phone: "(11) 95555-7890",
    contact_email: "eventos@woodsbar.com.br",
    notes: "Interesse em show no Dia dos Namorados",
    latitude: -23.5617,
    longitude: -46.6878,
  },
  {
    id: "mock-6",
    contractor_name: "Prefeitura de Ribeirão Preto",
    contractor_type: "Prefeitura",
    city: "Ribeirão Preto",
    state: "SP",
    venue_name: "Praça Central",
    event_date: "2026-06-19",
    fee: 120000,
    stage: "Contrato",
    contact_phone: "(16) 94444-1234",
    contact_email: "cultura@ribeiraopreto.sp.gov.br",
    notes: "Festa junina municipal",
    latitude: -21.1775,
    longitude: -47.8103,
  },
  {
    id: "mock-7",
    contractor_name: "Expo Londrina",
    contractor_type: "Festival",
    city: "Londrina",
    state: "PR",
    venue_name: "Parque Ney Braga",
    event_date: "2026-04-08",
    fee: 180000,
    stage: "Negociação",
    contact_phone: "(43) 93333-5678",
    contact_email: "shows@expolondrina.com.br",
    notes: "Negociando valor do cachê",
    latitude: -23.3045,
    longitude: -51.1696,
  },
  {
    id: "mock-8",
    contractor_name: "Caldas Country",
    contractor_type: "Festival",
    city: "Caldas Novas",
    state: "GO",
    venue_name: "Caldas Country Show",
    event_date: "2026-11-15",
    fee: 250000,
    stage: "Proposta",
    contact_phone: "(64) 92222-9012",
    contact_email: "artistas@caldascountry.com.br",
    notes: "Esperando retorno da proposta",
    latitude: -17.7419,
    longitude: -48.6278,
  },
];

export const mockEvents = [
  {
    id: "event-1",
    title: "Show São Paulo",
    city: "São Paulo",
    state: "SP",
    venue_name: "Anhangabaú",
    start_time: "2026-03-15T21:00:00",
    end_time: "2026-03-15T23:30:00",
    status: "negotiation",
    fee: 150000,
    contractor_name: "Prefeitura de São Paulo",
    latitude: -23.5505,
    longitude: -46.6333,
  },
  {
    id: "event-2",
    title: "Rodeio de Jaguariúna",
    city: "Jaguariúna",
    state: "SP",
    venue_name: "Parque de Eventos",
    start_time: "2026-05-10T22:00:00",
    end_time: "2026-05-11T00:30:00",
    status: "confirmed",
    fee: 200000,
    contractor_name: "Rodeio de Jaguariúna",
    latitude: -22.7059,
    longitude: -47.0025,
  },
  {
    id: "event-3",
    title: "Expo Londrina",
    city: "Londrina",
    state: "PR",
    venue_name: "Parque Ney Braga",
    start_time: "2026-04-08T21:00:00",
    end_time: "2026-04-08T23:30:00",
    status: "negotiation",
    fee: 180000,
    contractor_name: "Expo Londrina",
    latitude: -23.3045,
    longitude: -51.1696,
  },
  {
    id: "event-4",
    title: "Festa Junina Ribeirão",
    city: "Ribeirão Preto",
    state: "SP",
    venue_name: "Praça Central",
    start_time: "2026-06-19T20:00:00",
    end_time: "2026-06-19T23:00:00",
    status: "confirmed",
    fee: 120000,
    contractor_name: "Prefeitura de Ribeirão Preto",
    latitude: -21.1775,
    longitude: -47.8103,
  },
  {
    id: "event-5",
    title: "Bloco de Carnaval",
    city: "São Paulo",
    state: "SP",
    venue_name: "Av. Paulista",
    start_time: "2026-02-15T15:00:00",
    end_time: "2026-02-15T20:00:00",
    status: "confirmed",
    fee: 95000,
    contractor_name: "Bloco Sertanejo",
    latitude: -23.5618,
    longitude: -46.6557,
  },
];

export const mockContracts = [
  {
    id: "contract-1",
    lead_id: "mock-4",
    status: "signed",
    fee: 200000,
    payment_method: "PIX",
    document_url: "https://example.com/contract1.pdf",
  },
  {
    id: "contract-2",
    lead_id: "mock-6",
    status: "pending",
    fee: 120000,
    payment_method: "Transferência",
    document_url: null,
  },
];

// Monthly stats for charts
export const mockMonthlyStats = [
  { month: "Jan", shows: 3, revenue: 280000, leads: 12 },
  { month: "Fev", shows: 4, revenue: 350000, leads: 15 },
  { month: "Mar", shows: 5, revenue: 450000, leads: 18 },
  { month: "Abr", shows: 3, revenue: 320000, leads: 10 },
  { month: "Mai", shows: 6, revenue: 520000, leads: 22 },
  { month: "Jun", shows: 4, revenue: 400000, leads: 14 },
];

// Funnel stats
export const mockFunnelStats = [
  { stage: "Prospecção", count: 8, value: 480000 },
  { stage: "Contato", count: 5, value: 380000 },
  { stage: "Proposta", count: 4, value: 350000 },
  { stage: "Negociação", count: 3, value: 510000 },
  { stage: "Contrato", count: 2, value: 300000 },
  { stage: "Fechado", count: 6, value: 720000 },
];

export function formatMoneyBRL(value: number): string {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}
